<template>
    <div>
        index
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
        <p>index</p>
    </div>
</template>

<script>
export default {
    name: 'IndexPage'
}
</script>
